### ISSUE TITLE
About the baseline in Ablation Table 2(a).

### ISSUE THREAD

**Issue by HELLORPG** [BingfengYan/CO-MOT#1]
Hi, your method has really impressive results in extensive benchmarks. I've read your paper and have some questions about the baseline you mentioned in Table 2(a) row (a).

I evaluated MOTR's final checkpoint on DanceTrack val set, which got about ~52.0 HOTA. But your baseline has reached 63.8 HOTA, and this was a huge improvement. I wonder to know that **what technique improvements you have made over MOTR for your baseline**?
As far as I know, there are the following points:
1. You have changed the number of queries to 80.
2. Add CrowdHuman for joint training.
3. Change the training scheduler.
4. Use the anchor to generate the position embedding as MOTRv2 does.

Besides the above, is there anything else I did not mention but crucial for the final performance?

Looking forward to hearing from you, and thanks anyway.

**Comment by fengxiuyaun** [comment]
hi, First of all, thank you very much for your attention. Yes, our baseline is much higher than MOTR. We have also conducted experiments before to compare, and the reasons are similar to what you said: 1. Add CrowdHuman for joint training. 2. Change the training scheduler. 3. change the number of queries to 60. Among them, 1  probably increased by 3-4 points, and 2 increased by 3-4 points. We did not use the 4（Use the anchor to generate the position embedding as MOTRv2 does） you mentioned. Specifically, can you compare the configuration parameters of our code with MOTR's? such as, fp_ratio/sampler_lengths, etc.

**Comment by fengxiuyaun** [comment]
hi, First of all, thank you very much for your attention. Yes, our baseline is much higher than MOTR. We have also conducted experiments before to compare, and the reasons are similar to what you said: 1. Add CrowdHuman for joint training. 2. Change the training scheduler. 3. change the number of queries to 60. Among them, 1 probably increased by 3-4 points, and 2 increased by 3-4 points. We did not use the 4（Use the anchor to generate the position embedding as MOTRv2 does） you mentioned. Specifically, you  can compare the configuration parameters of our code with MOTR's, such as, fp_ratio/sampler_lengths, etc.

**Comment by fengxiuyaun** [comment]
hi, First of all, thank you very much for your attention. 

Yes, our baseline is much higher than MOTR. We have also conducted experiments before to compare, and the reasons are similar to what you said: 
     1. Add CrowdHuman for joint training. 
     2. Change the training scheduler. 
     3. change the number of queries to 60. 
 
Among them, 1 probably increased by 3-4 points, and 2 increased by 3-4 points. We did not use the 4（Use the anchor to generate the position embedding as MOTRv2 does）you mentioned. Specifically, you can compare the configuration parameters of our code with MOTR's, such as, fp_ratio/sampler_lengths, etc.

**Comment by HELLORPG** [comment]
Thanks for your reply!

About point 4, it is my fault. You just use a 4D reference point, unlike 2D in MOTR, right?
One more thing, I see that you use `--fp_ratio` and `--random_drop` in the configuration, as you say, but in `GQIM`, they are deprecated. Did you use this technique in the baseline but not in the final Co-MOT?

**Comment by fengxiuyaun** [comment]
“About point 4, it is my fault. You just use a 4D reference point, unlike 2D in MOTR, right?”-> yes.
“One more thing, I see that you use --fp_ratio and --random_drop in the configuration, as you say, but in GQIM, they are deprecated. Did you use this technique in the baseline but not in the final Co-MOT?” -> No, 
Except for the two points mentioned in the paper (COLA+Shadow), all other configurations are consistent with the baseline. such as, --fp_ratio/--random_drop also are not included in the baseline code.

**Comment by HELLORPG** [comment]
I got it. Thanks very much for your detailed reply!

**Comment by fengxiuyaun** [comment]
we can have more communication or even deeper cooperation in the future. ☺️☺️

**Comment by HELLORPG** [comment]
🎉 😃
