### ISSUE TITLE
计算资源

### ISSUE THREAD

**Issue by lebron-2016** [BingfengYan/CO-MOT#12]
尊敬的作者您好：

我在您的论文中看到您使用了8块V100-16G GPU，请问您在MOT17数据集上的训练时间大致是多少呢？

感谢！！

**Comment by fengxiuyaun** [comment]
大概3天

**Comment by lebron-2016** [comment]
> 大概3天

喔喔好的，还想问下模型的参数量大约是多少呢？

**Comment by fengxiuyaun** [comment]
> > 大概3天
> 
> 喔喔好的，还想问下模型的参数量大约是多少呢？

基本和deformable detr一致，我记得是195M
