### ISSUE TITLE
模型效果

### ISSUE THREAD

**Issue by lebron-2016** [BingfengYan/CO-MOT#13]
尊敬的作者您好：

我最近学习了您的工作，特别钦佩您的独到见解。但是在实测时，我遇到了这样的问题（类似MOT17的场景但是相机有比较剧烈的无规则运动）——视频开始时框很多，但是到后面越来越少（甚至有一帧中几十个目标都很显著，但是只有一个框的情况），MOTA非常低。但是用同样的设置在MOTR上训练、测试，效果要比您的模型好很多（MOTA和IDF1都高很多），想请教您这有可能是什么原因呢？理论上看您的改进相较于MOTR性能提升应该是很显著的，并且在MOT17数据集上您的算法也比MOTR好很多，这个问题困扰了我很长时间。期待您的回复！

衷心感谢您的帮助！！

**Comment by fengxiuyaun** [comment]
> 尊敬的作者您好：
> 
> 我最近学习了您的工作，特别钦佩您的独到见解。但是在实测时，我遇到了这样的问题（类似MOT17的场景但是相机有比较剧烈的无规则运动）——视频开始时框很多，但是到后面越来越少（甚至有一帧中几十个目标都很显著，但是只有一个框的情况），MOTA非常低。但是用同样的设置在MOTR上训练、测试，效果要比您的模型好很多（MOTA和IDF1都高很多），想请教您这有可能是什么原因呢？理论上看您的改进相较于MOTR性能提升应该是很显著的，并且在MOT17数据集上您的算法也比MOTR好很多，这个问题困扰了我很长时间。期待您的回复！
> 
> 衷心感谢您的帮助！！

你是原封不到在MOT17上训练的吗？readme里有我们release得weights，你可以参考一下。我在训练过程中倒是没有遇到类似的事情。

**Comment by lebron-2016** [comment]
> > 尊敬的作者您好：
> > 我最近学习了您的工作，特别钦佩您的独到见解。但是在实测时，我遇到了这样的问题（类似MOT17的场景但是相机有比较剧烈的无规则运动）——视频开始时框很多，但是到后面越来越少（甚至有一帧中几十个目标都很显著，但是只有一个框的情况），MOTA非常低。但是用同样的设置在MOTR上训练、测试，效果要比您的模型好很多（MOTA和IDF1都高很多），想请教您这有可能是什么原因呢？理论上看您的改进相较于MOTR性能提升应该是很显著的，并且在MOT17数据集上您的算法也比MOTR好很多，这个问题困扰了我很长时间。期待您的回复！
> > 衷心感谢您的帮助！！
> 
> 你是原封不到在MOT17上训练的吗？readme里有我们release得weights，你可以参考一下。我在训练过程中倒是没有遇到类似的事情。

不是MOT17，我用您提供的权重再试一下吧，感谢您的回复！！

**Comment by lebron-2016** [comment]
> > 尊敬的作者您好：
> > 我最近学习了您的工作，特别钦佩您的独到见解。但是在实测时，我遇到了这样的问题（类似MOT17的场景但是相机有比较剧烈的无规则运动）——视频开始时框很多，但是到后面越来越少（甚至有一帧中几十个目标都很显著，但是只有一个框的情况），MOTA非常低。但是用同样的设置在MOTR上训练、测试，效果要比您的模型好很多（MOTA和IDF1都高很多），想请教您这有可能是什么原因呢？理论上看您的改进相较于MOTR性能提升应该是很显著的，并且在MOT17数据集上您的算法也比MOTR好很多，这个问题困扰了我很长时间。期待您的回复！
> > 衷心感谢您的帮助！！
> 
> 你是原封不到在MOT17上训练的吗？readme里有我们release得weights，你可以参考一下。我在训练过程中倒是没有遇到类似的事情。

您好，我使用了您在readme中提供的MOT17数据集的权重在MOT17测试集上进行测试，效果依然很差，如下图所示为MOT17-01-SDP的第70帧，我感觉可能是我的设置出了问题。

![image](https://github.com/BingfengYan/CO-MOT/assets/80045218/6f5a52e6-2b8c-4e3d-8f56-4f7772ab2365)

我使用的是simplemot_inference.sh脚本文件，同时将submit_dance.py中的路径换成了MOT17的，配置文件如下图所示，

![image](https://github.com/BingfengYan/CO-MOT/assets/80045218/56cbd273-1dd2-4b87-9c1f-803b2c0c4c0e)

此外，在模型load时还遇到了这样的提示，

![image](https://github.com/BingfengYan/CO-MOT/assets/80045218/ab7c2fd2-9ebe-4957-a8ad-b936c2000bb7)

可以麻烦您帮忙看下吗？万分感谢！！

**Comment by lebron-2016** [comment]
> > 尊敬的作者您好：
> > 我最近学习了您的工作，特别钦佩您的独到见解。但是在实测时，我遇到了这样的问题（类似MOT17的场景但是相机有比较剧烈的无规则运动）——视频开始时框很多，但是到后面越来越少（甚至有一帧中几十个目标都很显著，但是只有一个框的情况），MOTA非常低。但是用同样的设置在MOTR上训练、测试，效果要比您的模型好很多（MOTA和IDF1都高很多），想请教您这有可能是什么原因呢？理论上看您的改进相较于MOTR性能提升应该是很显著的，并且在MOT17数据集上您的算法也比MOTR好很多，这个问题困扰了我很长时间。期待您的回复！
> > 衷心感谢您的帮助！！
> 
> 你是原封不到在MOT17上训练的吗？readme里有我们release得weights，你可以参考一下。我在训练过程中倒是没有遇到类似的事情。

作者您好，我现在找到问题了。之前预设的query数量太少了导致效果很差，我看到您在MOT17数据集上设置的是900个query，请问这个数字是如何确定的呢？如果换一个数据集的话怎么选择合适的query数量？十分感谢！！

**Comment by fengxiuyaun** [comment]
数了一下最大的人数，就随意写了一个值

**Comment by lebron-2016** [comment]
> 数了一下最大的人数，就随意写了一个值

了解了，感谢感谢！！
