### ISSUE TITLE
About COLA

### ISSUE THREAD

**Issue by MinorityA** [BingfengYan/CO-MOT#15]
Thank you for your excellent work. 

However, I am confused about which part of code using COLA for Decoder, cause my interpretation of the code suggests a uniform application across layers of Decoder. I apologize if I have overlooked any details in the documentation or code comments that might clarify this aspect. If possible, could you kindly provide further insight into where COLA is integrated within the decoder's architecture?

**Comment by MinorityA** [comment]
I am sorry I misunderstood the COLA and found it in the matching part.

**Comment by jeiva2000** [comment]
Hi, could you tell me where is the COLA code, I'm a bit confused if there is some code in the decoded layers I'm passing or if tail is implicit in the association.

**Comment by MinorityA** [comment]
> Hi, could you tell me where is the COLA code, I'm a bit confused if there is some code in the decoded layers I'm passing or if tail is implicit in the association.

Based on my interpretation, you could check code from the 220 line of motr_co.py, I think they used aux_ouputs of each layer here to match all gt_instances to realize COLA.

**Comment by jeiva2000** [comment]
thank you so much.
