### ISSUE TITLE
BDD100K release

### ISSUE THREAD

**Issue by carpeug** [BingfengYan/CO-MOT#3]
Hi,
I am an Italian student at the University of Salerno who is doing a thesis in autonomous vehicle driving concerning transformer-based tracking techniques. While studying the state-of-the-art I came across your paper. I would be very grateful if it would be possible to have your model trained on BDD100K. How soon will it be published?
Thank you in advance.

**Comment by fengxiuyaun** [comment]
Here. https://drive.google.com/file/d/1WEDtLE-dj0cwsk_dMmzx_EBESmAmCQ-G/view?usp=drive_link.
If you have any question, please tell me.

**Comment by carpeug** [comment]
> Here. https://drive.google.com/file/d/1WEDtLE-dj0cwsk_dMmzx_EBESmAmCQ-G/view?usp=drive_link. If you have any question, please tell me.

Thank you very much for your helpfulness!

**Comment by goldentimecoolk** [comment]
> Here. https://drive.google.com/file/d/1WEDtLE-dj0cwsk_dMmzx_EBESmAmCQ-G/view?usp=drive_link. If you have any question, please tell me.

Hi @carpeug, I'm new to the end to end MOTR-like tracker. Your improvement is amazing and inspiring. Could you please share the weights trained on the MOT17 dataset? Or what is your plan to make it public?
Thank you!

**Comment by fengxiuyaun** [comment]
> 

Here. https://drive.google.com/file/d/1zWn2kz_ikpel32_RwpBelGQIuLVBa69f/view?usp=sharing

**Comment by goldentimecoolk** [comment]
> > 
> 
> Here. https://drive.google.com/file/d/1zWn2kz_ikpel32_RwpBelGQIuLVBa69f/view?usp=sharing

@carpeug Thank you very much!
