### ISSUE TITLE
A question about training process.

### ISSUE THREAD

**Issue by balabooooo** [BingfengYan/CO-MOT#4]
Thank you for your excellent work!
I have a question about the training process in figure 3.
Why the matched IDs of different queries keeps changing in different layers? 
Thank you in advance.

**Comment by fengxiuyaun** [comment]
It is not necessary to change, rather the result of Hungarian matching. This is just to illustrate that the output  of different decoder layers may be different, for one query.

**Comment by balabooooo** [comment]
Thank you very much !
