### ISSUE TITLE
Question about the training.

### ISSUE THREAD

**Issue by goldentimecoolk** [BingfengYan/CO-MOT#5]
Hi, Yan, thanks for your great effort to make your work public. I have a question after runing your script to train the CO-MOT model on dancetrack. In the `motr_co.py`, because 5 images act as one unit in the loop, the flag [`is_last`](https://github.com/BingfengYan/CO-MOT/blob/main/models/motr_co.py#L760) is always `True`, so that the module `GQIM` is awalys not included in the training stage. At the same time, from the [matching strategy](https://github.com/BingfengYan/CO-MOT/blob/main/models/motr_co.py#L185), the training seems to be the task of detection rather than tracking. I wonder if my understanding is right? ( If right, then how to train the tracking task?)
Thank you.

**Comment by fengxiuyaun** [comment]
1st -> forward [+loss] ->  gqim -> 2st -> froward [+loss] -> gqim-> XXXX -> 5st -> froward  [+loss] -> gqim

The entire process of training with 5 images is shown above. It can be seen that the first four GQIMs were supervised, while the last one was not.  The gradient of the first GQIM comes from the second loss.

**Comment by goldentimecoolk** [comment]
Thanks for your quick reply. Now I understand the process when training 5 images described above. But in the code, it might not run as expectation. 

When debugging the code, I found it is because the [loop](https://github.com/BingfengYan/CO-MOT/blob/main/models/motr_co.py#L757) takes five images as one unit and there is one loop for five images, which is shown in the following picture. So the flag `is_last` is awalys True. In this situation, the `GQIM` module is not called in the training process. 

Could it be resulted by the configuration? (my personal guess)

![2023-07-27 19-52-01 的屏幕截图](https://github.com/BingfengYan/CO-MOT/assets/39372277/ef9e4cc2-ac64-44cc-a9fd-65824721a2a4)

**Comment by fengxiuyaun** [comment]
I'm very sorry, I made a mistake in this code while organizing it.  https://github.com/BingfengYan/CO-MOT/blob/7624236c9282c0dd6bbf367a45645e68af61ad20/util/misc.py#L281 

 It should be modified：
def mot_collate_fn(batch: List[dict]) -> dict:
    ret_dict = {}
    for key in list(batch[0].keys()):
        assert not isinstance(batch[0][key], Tensor)
        ret_dict[key] = [img_info[key] for img_info in batch]
        if  isinstance(ret_dict[key][0], list):
            ret_dict[key] = list(map(list, zip(*ret_dict[key])))
    return ret_dict

**Comment by goldentimecoolk** [comment]
Thank you! It works fine now.

**Comment by goldentimecoolk** [comment]
Hi, @fengxiuyaun , in the qim module you utilized, I have a question.
In the fucntion [`_select_active_tracks`](https://github.com/BingfengYan/CO-MOT/blob/main/models/qim.py#L256C70-L256C70), why not directly use `track_instances.obj_idxes.reshape(-1, g_size, bs)>=0).any(1) | (track_instances.scores.reshape(-1, g_size, bs)> 0.5).any(1)` as the `active_index`, but use them to get the number of active queries and select updated queries upon `track_instances.scores` based on the number? I debug this point and find the two results are different. What is the consideration of this modification? And what is the gain by this modification?

**Comment by fengxiuyaun** [comment]
You are right. Both methods are feasible, and the final training effect is almost the same.

**Comment by goldentimecoolk** [comment]
OK, thank you for the response.
