### ISSUE TITLE
How to get the summarized HOTA?

### ISSUE THREAD

**Issue by goldentimecoolk** [BingfengYan/CO-MOT#6]
Hi, Yan, when the evaluation is called during training process, there is an error
```
    return float(res_eval[0]['MotChallenge2DBox']['']['COMBINED_SEQ']['pedestrian']['summaries'][0]['HOTA'])
KeyError: 'summaries'
```
Is there any modification to the TrackEval files when calculating the final HOTA?

**Comment by goldentimecoolk** [comment]
The bug is fixed when I replace the output with
```python
return float(np.mean(res_eval[0]['MotChallenge2DBox']['']['COMBINED_SEQ']['pedestrian']['HOTA']['HOTA']))
```

**Comment by fengxiuyaun** [comment]
Here: https://github.com/fengxiuyaun/TrackEval
