### ISSUE TITLE
Question about CUDA version

### ISSUE THREAD

**Issue by carpeug** [BingfengYan/CO-MOT#7]
Hi, I see in your README.md/Requirements that cudatoolkit=10.2 is needed. However, I have CUDA 12.0 and when I try to build MultiScaleDeformableAttention i get the following error "RuntimeError: The detected CUDA version (12.0) mismatches the version that was used to compile PyTorch (10.2). Please make sure to use the same CUDA versions.". 
Is there any way to solve this? Do I need to downgrade my local CUDA to version 10.2 or can I do something else?
Thank you very much in advance.

**Comment by carpeug** [comment]
However, this problem arose because having the .pth file I need to instantiate your model class in order to use it and I need to import its class in order to instantiate it. However, having the .pt (traced model) file would solve this problem.

**Comment by fengxiuyaun** [comment]
Thank you very much for your question. I would recommend that you use conda to install a separate environment. This will help avoid conflicts with other environments and allow you to better manage your Python environment. Thank you for your support!

**Comment by carpeug** [comment]
Hi, thank you for your reply. In fact I am using a conda environment, as specified in the README.md file, but still I am having this problem.

**Comment by fengxiuyaun** [comment]
Maybe, you need reinstall your envs
