### ISSUE TITLE
Testing on Waymo

### ISSUE THREAD

**Issue by carpeug** [BingfengYan/CO-MOT#8]
Hi, how can I make inference with CO-MOT on the Waymo dataset? In the README.md file it only refers to DanceTrack

**Comment by fengxiuyaun** [comment]
You need to modify “ListImgDataset” in submit.py

**Comment by carpeug** [comment]
Did you mean submit_dance.py? Because i can't find submit.py

**Comment by fengxiuyaun** [comment]
YES.

**Comment by carpeug** [comment]
Hi, when executing simple_inference.sh with my Waymo dataset, should I still pass configs/motrv2ch_uni5cost3ggoon.args? Or are there other configuration files for a different dataset than the ones it was pre-trained on?

**Comment by carpeug** [comment]
Hi, when executing simple_inference.sh with my Waymo dataset, should I still pass configs/motrv2ch_uni5cost3ggoon.args? Or are there other configuration files for a different dataset than the ones it was pre-trained on?
