### ISSUE TITLE
Occupancy of the model

### ISSUE THREAD

**Issue by carpeug** [BingfengYan/CO-MOT#9]
Hi, 
I would like to know what is the memory occupancy of the model once it is instantiated. I know that the weights file of the model trained on BDD100K is 303MB.
Thank you really much in advance.

**Comment by fengxiuyaun** [comment]
Train：about 12G

**Comment by carpeug** [comment]
And for inference ?

**Comment by fengxiuyaun** [comment]
I remember it's about 4G
